global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:8404']

  - job_name: 'haproxy-exporter'
    static_configs:
      - targets: ['haproxy-exporter:9101']
